#!/bin/bash
docker run \
    --runtime nvidia \
    -it \
    --rm \
    -v $HOME:$HOME \
    -e PYTHONPATH=$PYTHONPATH \
    -e HOSTNAME=`hostname` \
    --user jetson \
    python3-gpu-${USER} bash -c "cd `pwd` && python3 $*"
